export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const FETCH_PRODUCTS_DETAIL_SUCCESS = 'FETCH_PRODUCTS_DETAIL_SUCCESS';
export const FETCH_PRODUCTS_DETAIL_FAIL = 'FETCH_PRODUCTS_DETAIL_FAIL';